#!/usr/bin/env bash
# shellcheck disable=SC2009

for pid in /proc/[0-9]*; do
    cmd=$(cat "$pid/cmdline" 2>/dev/null)
    if [[ $cmd == *7-highlander* ]]; then
        kill -9 "$pid" 2>/dev/null
    fi
done
