#!/usr/bin/env bash
# shellcheck disable=SC2009
echo $$ > /tmp/myscript.pid

trap 'echo "OK"' SIGTERM

trap 'echo "Y U no love me?!"' SIGINT

trap 'rm -f /tmp/myscript.pid; exit' SIGQUIT

while true; do
    echo "To infinity and beyond"
    sleep 2
done
