#!/usr/bin/env bash
# shellcheck disable=SC2009

PID_FILE="/tmp/myscript.pid"

# Skriptin PID-sini fayla yazırıq
echo $$ > "$PID_FILE"

# SIGINT (Ctrl+C) üçün trap
trap 'echo "Y U no love me?!"' SIGINT

# SIGTERM üçün trap
trap 'echo "I hate the kill command"' SIGTERM

# SIGQUIT və SIGTERM üçün faylı silib çıxmaq
trap 'rm -f "$PID_FILE"; exit' SIGQUIT SIGTERM

# Sonsuz loop
while true; do
    echo "To infinity and beyond"
    sleep 2
done
